go:
    cgo: true
repository:
    path: github.com/hungerstation/pgbouncer_exporter
build:
    flags: -a -tags 'netgo static_build'
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - linux/arm
        - linux/arm64
